name: Package unstable build
on: 
  push
jobs:
  first-section:
    name: Set up Node
    runs-on: ubuntu-latest
    uses: actions/setup-node@v3
    with:
        node-version: 16.15.0
    run: npm install @vscode/vsce
  second-section:
    title: Package this masterpiece
    run: vsce package --pre-release -o "steamyfish-beta.vsix"
  third-section:
    name: Archive code coverage results
    uses: actions/upload-artifact@v3
    with:
      name: steamy_fish-beta
      path: steamyfish-beta.vsix
      retention-days: 14