name: Package unstable build
on: 
  push:
    branches:
      "master"
jobs:
  package:
    name: Making package...
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Install `@vscode/vsce`
        run: npm install -g @vscode/vsce
      - name: Clone this repository
        run: git clone https://github.com/VitalikLevin/steamyfish-theme.git
      - name: What files are there?
        run: ls
      - name: Using `vsce`
        id: masterpiece
        run: vsce package
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.masterpiece.outputs.filePath }}
          path: ${{ steps.masterpiece.outputs.filePath }}
          retention-days: 21